### ISSUE TITLE
Fix failing tests when webpack mode="production"

### ISSUE THREAD

**Issue by Coteh** [Coteh/mcu-rewatch#14]
These tests fail when `mode: "production"` in `webpack.config.js`:

```
1) should not have 'grayscale' class if movie has been watched
     MCUMovie
     AssertionError: expected [ 'movie', 'grayscale' ] to not include 'grayscale'
    at Context.<anonymous> (webpack:///test/MCUMovie.spec.ts:46:41 <- assets/js/test/MCUMovie.spec.bundle.js:580:1011511)

2) should appear if both loaded and available to show
     MCUMovie
     AssertionError: expected 'none' to not equal 'none'
    at Context.<anonymous> (webpack:///test/MCUMovie.spec.ts:59:53 <- assets/js/test/MCUMovie.spec.bundle.js:580:1011701)

3) should populate the dropdown with options
     MCUSelector
     AssertionError: expected 0 to equal 2
    at Context.<anonymous> (webpack:///test/MCUSelector.spec.ts:44:36 <- assets/js/test/MCUSelector.spec.bundle.js:588:2970)

4) should invoke save operation for correct ordering preference when selected
     MCUSelector
     AssertionError: did not invoke save for the correct ordering: expected undefined to equal 'test2'
    at Context.<anonymous> (webpack:///test/MCUSelector.spec.ts:63:36 <- assets/js/test/MCUSelector.spec.bundle.js:588:3348)
    at s (webpack:///node_modules/sinon-test/dist/sinon-test.js:146 <- assets/js/test/MCUSelector.spec.bundle.js:588:1293)
    at Context.<anonymous> (webpack:///node_modules/sinon-test/dist/sinon-test.js:166 <- assets/js/test/MCUSelector.spec.bundle.js:588:1578)
```

Investigate and fix.

**Comment by Coteh** [comment]
I was taking a look at https://vue-test-utils.vuejs.org/guides/getting-started.html#what-about-nexttick and decided to try out `Vue.nextTick()` to see if perhaps something is happening in production build that is causing the DOM to be updated differently. Turns out this seems to be the case.

I found rather anecdotally that this issue can be solved by changing the function that's calling `setData` to be `async`. If the function that's calling `setData` is `beforeEach`'s callback, then all the tests will have the DOM update applied. If you want to use the results of the DOM update in the same function, then `await Vue.nextTick()` will need to be called first before you can use them.

As mentioned in the above document on vue-test-utils documentation, `Vue.nextTick()` is asynchronous and as a result any failures will not be propagated if there's a failure within the callback or promise resolution of the `Vue.nextTick()`. However, by making the function `async` and calling `await Vue.nextTick()`, any subsequent failures will in fact be propagated.
